app:
  action_timeout: 60
  action_wait_time: 10
  ready_check_max_tries: 3
  close_wait_time: 1
element:
  default_confidence: 0.7
  pixel_size: [1, 1]
controller:
  default_click_times: 1
  default_max_tries: 2
  click_coord_times: 1
